# Generated by Django 4.2.5 on 2024-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_now', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='rentpost',
            name='rent_request',
        ),
        migrations.AddField(
            model_name='rentpost',
            name='rent_request',
            field=models.ManyToManyField(to='rent_now.rentrequest'),
        ),
    ]
